# Generated by Django 5.0.1 on 2024-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакты', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='building',
            field=models.CharField(default=1, max_length=5, verbose_name='номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=11, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default=1, max_length=100, verbose_name='улица'),
            preserve_default=False,
        ),
    ]
