# Generated by Django 5.0.1 on 2024-01-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_product_options_product_model_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('Factory', 'Завод'), ('Company', 'ИП'), ('Retail', 'Розничная сеть')], max_length=7, verbose_name='тип звена сети')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('level', models.IntegerField(default=0, verbose_name='уровень иерархии')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.contact', verbose_name='контакты')),
                ('products', models.ManyToManyField(blank=True, to='network.product', verbose_name='продукты')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.link', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'ИП',
                'verbose_name_plural': 'ИП',
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
