# Generated by Django 5.0.1 on 2024-01-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_link_delete_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
    ]
