# Generated by Django 5.0.1 on 2024-01-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_link_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='network.link', verbose_name='звено'),
        ),
    ]
